---
title: Components
description: Removal of certain Windows components
privilege: TrustedInstaller
actions:


 - !taskKill: {name: "explorer"}
# - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband', value: 'Favorites', type: REG_BINARY, data: '00A40100003A001F80C827341F105C1042AA032EE45287D668260001002600EFBE120000001A1E97454EEFD801757130704EEFD8015EB737704EEFD801140056003100000000006355693411005461736B42617200400009000400EFBE63556934635569342E0000009D8A0100000001000000000000000000000000000000A29F33005400610073006B00420061007200000016001201320097010000A754662A200046494C4545587E312E4C4E4B00007C0009000400EFBE63556934635569342E0000009E8A0100000001000000000000000000520000000000A413A200460069006C00650020004500780070006C006F007200650072002E006C006E006B00000040007300680065006C006C00330032002E0064006C006C002C002D003200320030003600370000001C00120000002B00EFBE22283A704EEFD8011C00420000001D00EFBE02004D006900630072006F0073006F00660074002E00570069006E0064006F00770073002E004500780070006C006F0072006500720000001C00260000001E00EFBE0200530079007300740065006D00500069006E006E006500640000001C000000FF'}
# - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband', value: 'FavoritesResolve', type: REG_BINARY, data: '330300004C0000000114020000000000C0000000000000468300800020000000E7E332704EEFD80122283A704EEFD8015CF4E1FBD161D801970100000000000001000000000000000000000000000000A0013A001F80C827341F105C1042AA032EE45287D668260001002600EFBE120000001A1E97454EEFD801757130704EEFD8015EB737704EEFD801140056003100000000006355693411005461736B42617200400009000400EFBE63556934635569342E0000009D8A0100000001000000000000000000000000000000A29F33005400610073006B00420061007200000016000E01320097010000A754662A200046494C4545587E312E4C4E4B00007C0009000400EFBE63556934635569342E0000009E8A0100000001000000000000000000520000000000A413A200460069006C00650020004500780070006C006F007200650072002E006C006E006B00000040007300680065006C006C00330032002E0064006C006C002C002D003200320030003600370000001C00220000001E00EFBE02005500730065007200500069006E006E006500640000001C00120000002B00EFBE22283A704EEFD8011C00420000001D00EFBE02004D006900630072006F0073006F00660074002E00570069006E0064006F00770073002E004500780070006C006F0072006500720000001C0000009C0000001C000000010000001C0000002D000000000000009B000000110000000300000013EBC8041000000000433A5C55736572735C4D634E696E5C417070446174615C526F616D696E675C4D6963726F736F66745C496E7465726E6574204578706C6F7265725C517569636B204C61756E63685C557365722050696E6E65645C5461736B4261725C46696C65204578706C6F7265722E6C6E6B000060000000030000A058000000000000006465736B746F702D666A63716F626D00A84D9F7C73D4F344BF15FAA23DFD8B4733F18E66405BED11AA54000C29341E2EA84D9F7C73D4F344BF15FAA23DFD8B4733F18E66405BED11AA54000C29341E2E45000000090000A03900000031535053B1166D44AD8D7048A748402EA43D788C1D0000006800000000480000009B7B87BF89DF6547B6A80DC335F1C9BF000000000000000000000000'}

 # Edge
 - !taskKill: {name: "MicrosoftEdgeUpdate", option: "remove-edge"}
 - !taskKill: {name: "msedge", option: "remove-edge"}
 - !taskKill: {name: "MicrosoftEdge*", option: "remove-edge"}
 - !taskKill: {name: "setup", pathContains: "\\Edge", option: "remove-edge"}
 - !taskKill: {name: "msedgewebview2", option: "remove-edge"}
 - !service: {name: "edgeupdate", operation: delete, option: "remove-edge"}
 - !service: {name: "edgeupdatem", operation: delete, option: "remove-edge"}
 - !service: {name: "MicrosoftEdgeElevationService", operation: delete, option: "remove-edge"} 
 - !cmd: {command: '"edge.bat"', runas: trustedInstaller, exeDir: true, wait: true, option: "remove-edge"}
 - !appx: {name: 'Microsoft.MicrosoftEdge_8wekyb3d8bbwe', type: family, option: "remove-edge"}
 - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe', operation: add, option: "remove-edge"}
 - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.MicrosoftEdge_8wekyb3d8bbwe', operation: add, option: "remove-edge"}
 
 # Onedrive
 - !status: {status: 'Removing OneDrive'}
 - !taskKill: {name: "OneDriveStandaloneUpdater"}
 - !taskKill: {name: "OneDriveSetup"}
 - !taskKill: {name: "OneDrive*"}
 - !service: {name: "OneSyncSvc*", operation: delete}

 - !cmd: {command: '"oned.bat"', exeDir: true, runas: trustedInstaller, wait: true}
 - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'OneDrive', operation: delete}
 - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'OneDriveSetup', operation: delete}
 - !file: {path: "%windir%\\System32\\OneDriveSetup.exe"}
 - !file: {path: "%windir%\\SysWOW64\\OneDriveSetup.exe"}
 - !file: {path: "%windir%\\SysWOW64\\OneDriveSettingSyncProvider.dll"}
 - !file: {path: "%SystemDrive%\\OneDriveTemp"}
 - !file: {path: "%ProgramData%\\Microsoft OneDrive"}


 # AI mumbo jumbo
 - !scheduledTask:
    path: "\\Microsoft\\Windows\\WindowsAI\\Recall"
    operation: deleteFolder
 - !scheduledTask:
    path: "\\Microsoft\\Windows\\WindowsAI\\Settings"
    operation: deleteFolder
 - !scheduledTask:
    path: "\\Microsoft\\Windows\\WindowsAI"
    operation: deleteFolder

 - !taskKill: {name: 'ai.exe'}
 - !taskKill: {name: 'Copilot.exe'}
 - !taskKill: {name: 'aihost.exe'}
 - !taskKill: {name: 'aicontext.exe'}
 - !taskKill: {name: 'ClickToDo.exe'}
 - !taskKill: {name: 'aixhost.exe'}
 - !taskKill: {name: 'WorkloadsSessionHost.exe'}

 - !service:
    name: "WSAIFabricSvc"
    operation: delete

 - !appx: {name: '*MicrosoftWindows.Client.AIX*', type: family}
 - !appx: {name: '*Microsoft.Copilot*', type: family}
 - !appx: {name: '*Microsoft.Windows.Copilot*', type: family}
 - !appx: {name: '*Client.CoPilot*', type: family}
 - !appx: {name: '*Ai.Copilot*', type: family}
 - !appx: {name: '*Client.CoreAI*', type: family}

 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot', value: 'TurnOffWindowsCopilot', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'DisableAIDataAnalysis', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'AllowRecallEnablement', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'DisableClickToDo', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'TurnOffSavingSnapshots', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'DisableSettingsAgent', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\Shell\Copilot\BingChat', value: 'IsUserEligible', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\Shell\Copilot', value: 'IsCopilotAvailable', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\Shell\Copilot', value: 'CopilotDisabledReason', type: REG_SZ, data: 'FeatureIsDisabled'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot', value: 'TurnOffWindowsCopilot', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'DisableAIDataAnalysis', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'AllowRecallEnablement', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'DisableClickToDo', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'TurnOffSavingSnapshots', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\WindowsAI', value: 'DisableSettingsAgent', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\Shell\Copilot\BingChat', value: 'IsUserEligible', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\Shell\Copilot', value: 'IsCopilotAvailable', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\Shell\Copilot', value: 'CopilotDisabledReason', type: REG_SZ, data: 'FeatureIsDisabled'}
 - !registryValue: {path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowCopilotButton', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKCU\Software\Microsoft\input\Settings', value: 'InsightsEnabled', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'DisableSearchBoxSuggestions', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'CopilotCDPPageContext', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'CopilotPageContext', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'HubsSidebarEnabled', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'CopilotPageContext', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'EdgeEntraCopilotPageContext', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'Microsoft365CopilotChatIconEnabled', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'EdgeHistoryAISearchEnabled', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'ComposeInlineEnabled', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Edge', value: 'GenAILocalFoundationalModelSettings', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings', value: 'AutoOpenCopilotLargeScreens', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\generativeAI', value: 'Value', type: REG_SZ, data: 'Deny'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy', value: 'LetAppsAccessGenerativeAI', type: REG_DWORD, data: '2'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy', value: 'LetAppsAccessSystemAIModels', type: REG_DWORD, data: '2'}
 - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsCopilot', value: 'AllowCopilotRuntime', type: REG_DWORD, data: '0'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Paint', value: 'DisableImageCreator', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Paint', value: 'DisableCocreator', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Paint', value: 'DisableGenerativeFill', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Paint', value: 'DisableGenerativeErase', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Paint', value: 'DisableRemoveBackground', type: REG_DWORD, data: '1'}
 - !registryValue: {path: 'HKLM\SOFTWARE\Policies\WindowsNotepad', value: 'DisableAIFeatures', type: REG_DWORD, data: '1'}
 - !registryKey: {path: 'HKCR\ms-office-ai', operation: delete}
 - !registryKey: {path: 'HKCR\ms-copilot', operation: delete}
 - !registryKey: {path: 'HKCR\ms-clicktodo', operation: delete}